spring:
  application:
    name: eureka-cus-client
server:
  port: 8764
feign.hystrix.enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.101.155.20:8761/eureka/
#     defaultZone: http://localhost:8762/eureka/