spring:
  application:
    name: demo-feign-freeservice
server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.101.155.20:8761/eureka/
#      defaultZone: http://localhost:8762/eureka/
